# Generated by Django 5.2.1 on 2025-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                ("security_id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker_symbol", models.CharField(max_length=20, unique=True)),
                (
                    "isin",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("security_name", models.CharField(max_length=255)),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "security_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_api_update", models.DateTimeField(blank=True, null=True)),
                ("benchmark", models.BooleanField(default=False)),
                ("expert", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Wertpapier",
                "verbose_name_plural": "Wertpapiere",
                "db_table": "wp_portf_securities",
                "ordering": ["security_name"],
            },
        ),
    ]
