# Generated by Django 5.2.1 on 2025-05-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_date", models.DateField()),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "adj_close_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="portfolio_app.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historischer Kurs",
                "verbose_name_plural": "Historische Kurse",
                "db_table": "wp_portf_historical_prices",
                "ordering": ["security", "price_date"],
                "unique_together": {("security", "price_date")},
            },
        ),
    ]
