# Generated by Django 5.2.1 on 2025-05-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_historicalprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprice",
            name="id",
        ),
        migrations.AddField(
            model_name="historicalprice",
            name="price_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicalprice",
            name="adj_close_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprice",
            name="close_price",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalprice",
            name="high_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprice",
            name="low_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprice",
            name="open_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprice",
            name="security",
            field=models.ForeignKey(
                db_column="security_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historical_prices",
                to="portfolio_app.security",
            ),
        ),
    ]
