# Generated by Django 5.2.1 on 2025-05-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0003_remove_historicalprice_id_historicalprice_price_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="last_api_update",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="security",
            name="ticker_symbol",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="security",
            unique_together={("ticker_symbol", "exchange")},
        ),
    ]
