# Generated by Django 5.2.1 on 2025-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0004_alter_security_last_api_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
