# Generated by Django 5.2.1 on 2025-05-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0005_security_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dividend",
            fields=[
                ("dividend_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ex_dividend_date",
                    models.DateField(verbose_name="Ex-Dividende Datum"),
                ),
                (
                    "amount_per_share",
                    models.DecimalField(
                        db_column="amount_per_share",
                        decimal_places=4,
                        max_digits=18,
                        verbose_name="Betrag pro Aktie",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="Zahltag"),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="portfolio_app.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dividende",
                "verbose_name_plural": "Dividenden",
                "db_table": "wp_portf_dividends",
                "ordering": ["security", "-ex_dividend_date"],
            },
        ),
    ]
