# Generated by Django 5.2.1 on 2025-05-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0006_dividend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Split",
            fields=[
                ("split_id", models.AutoField(primary_key=True, serialize=False)),
                ("split_date", models.DateField(verbose_name="Split-Datum")),
                (
                    "split_ratio_str",
                    models.CharField(
                        max_length=20, verbose_name="Split-Verhältnis (Text)"
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="portfolio_app.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktiensplit",
                "verbose_name_plural": "Aktiensplits",
                "db_table": "wp_portf_splits",
                "ordering": ["security", "-split_date"],
                "unique_together": {("security", "split_date")},
            },
        ),
    ]
