# Generated by Django 5.2.1 on 2025-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0007_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividend",
            name="declaration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Deklarationsdatum"
            ),
        ),
        migrations.AddField(
            model_name="dividend",
            name="dividend_currency",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Währung der Dividende",
            ),
        ),
        migrations.AddField(
            model_name="dividend",
            name="period",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Dividendenperiode (z.B. Quarterly)",
            ),
        ),
        migrations.AddField(
            model_name="dividend",
            name="record_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Record-Datum (Stichtag)"
            ),
        ),
        migrations.AlterField(
            model_name="dividend",
            name="amount_per_share",
            field=models.DecimalField(
                decimal_places=4, max_digits=18, verbose_name="Betrag pro Aktie"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dividend",
            unique_together={("security", "ex_dividend_date", "amount_per_share")},
        ),
    ]
