# Generated by Django 5.2.1 on 2025-05-25 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0008_dividend_declaration_date_dividend_dividend_currency_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("portfolio_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "portfolio_name",
                    models.CharField(max_length=255, verbose_name="Portfolioname"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Erstellungsdatum"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt geändert"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "db_table": "wp_portf_portfolios",
                "ordering": ["portfolio_name"],
            },
        ),
        migrations.CreateModel(
            name="TargetWeight",
            fields=[
                (
                    "target_weight_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "target_weight",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        verbose_name="Zielgewichtung (%)",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        db_column="portfolio_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_weights",
                        to="portfolio_app.portfolio",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        db_column="security_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_weights",
                        to="portfolio_app.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zielgewichtung",
                "verbose_name_plural": "Zielgewichtungen",
                "db_table": "wp_portf_target_weights",
                "ordering": ["portfolio", "security"],
                "unique_together": {("portfolio", "security")},
            },
        ),
    ]
