# Generated by Django 5.2.1 on 2025-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0009_portfolio_targetweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="expert",
            field=models.BooleanField(default=False, verbose_name="Expertenportfolio"),
        ),
    ]
